// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Mist-wu/sub2api/ent/predicate"
	"github.com/Mist-wu/sub2api/ent/userimagegeneration"
)

// UserImageGenerationDelete is the builder for deleting a UserImageGeneration entity.
type UserImageGenerationDelete struct {
	config
	hooks    []Hook
	mutation *UserImageGenerationMutation
}

// Where appends a list predicates to the UserImageGenerationDelete builder.
func (_d *UserImageGenerationDelete) Where(ps ...predicate.UserImageGeneration) *UserImageGenerationDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *UserImageGenerationDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UserImageGenerationDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *UserImageGenerationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(userimagegeneration.Table, sqlgraph.NewFieldSpec(userimagegeneration.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// UserImageGenerationDeleteOne is the builder for deleting a single UserImageGeneration entity.
type UserImageGenerationDeleteOne struct {
	_d *UserImageGenerationDelete
}

// Where appends a list predicates to the UserImageGenerationDelete builder.
func (_d *UserImageGenerationDeleteOne) Where(ps ...predicate.UserImageGeneration) *UserImageGenerationDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *UserImageGenerationDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{userimagegeneration.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UserImageGenerationDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
