// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Mist-wu/sub2api/ent/user"
	"github.com/Mist-wu/sub2api/ent/userimagegeneration"
)

// UserImageGenerationCreate is the builder for creating a UserImageGeneration entity.
type UserImageGenerationCreate struct {
	config
	mutation *UserImageGenerationMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *UserImageGenerationCreate) SetUserID(v int64) *UserImageGenerationCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetPrompt sets the "prompt" field.
func (_c *UserImageGenerationCreate) SetPrompt(v string) *UserImageGenerationCreate {
	_c.mutation.SetPrompt(v)
	return _c
}

// SetRevisedPrompt sets the "revised_prompt" field.
func (_c *UserImageGenerationCreate) SetRevisedPrompt(v string) *UserImageGenerationCreate {
	_c.mutation.SetRevisedPrompt(v)
	return _c
}

// SetNillableRevisedPrompt sets the "revised_prompt" field if the given value is not nil.
func (_c *UserImageGenerationCreate) SetNillableRevisedPrompt(v *string) *UserImageGenerationCreate {
	if v != nil {
		_c.SetRevisedPrompt(*v)
	}
	return _c
}

// SetModel sets the "model" field.
func (_c *UserImageGenerationCreate) SetModel(v string) *UserImageGenerationCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_c *UserImageGenerationCreate) SetNillableModel(v *string) *UserImageGenerationCreate {
	if v != nil {
		_c.SetModel(*v)
	}
	return _c
}

// SetMimeType sets the "mime_type" field.
func (_c *UserImageGenerationCreate) SetMimeType(v string) *UserImageGenerationCreate {
	_c.mutation.SetMimeType(v)
	return _c
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (_c *UserImageGenerationCreate) SetNillableMimeType(v *string) *UserImageGenerationCreate {
	if v != nil {
		_c.SetMimeType(*v)
	}
	return _c
}

// SetImageData sets the "image_data" field.
func (_c *UserImageGenerationCreate) SetImageData(v []byte) *UserImageGenerationCreate {
	_c.mutation.SetImageData(v)
	return _c
}

// SetImageSha256 sets the "image_sha256" field.
func (_c *UserImageGenerationCreate) SetImageSha256(v string) *UserImageGenerationCreate {
	_c.mutation.SetImageSha256(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserImageGenerationCreate) SetCreatedAt(v time.Time) *UserImageGenerationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserImageGenerationCreate) SetNillableCreatedAt(v *time.Time) *UserImageGenerationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *UserImageGenerationCreate) SetUser(v *User) *UserImageGenerationCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the UserImageGenerationMutation object of the builder.
func (_c *UserImageGenerationCreate) Mutation() *UserImageGenerationMutation {
	return _c.mutation
}

// Save creates the UserImageGeneration in the database.
func (_c *UserImageGenerationCreate) Save(ctx context.Context) (*UserImageGeneration, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserImageGenerationCreate) SaveX(ctx context.Context) *UserImageGeneration {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserImageGenerationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserImageGenerationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserImageGenerationCreate) defaults() {
	if _, ok := _c.mutation.Model(); !ok {
		v := userimagegeneration.DefaultModel
		_c.mutation.SetModel(v)
	}
	if _, ok := _c.mutation.MimeType(); !ok {
		v := userimagegeneration.DefaultMimeType
		_c.mutation.SetMimeType(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := userimagegeneration.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserImageGenerationCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserImageGeneration.user_id"`)}
	}
	if _, ok := _c.mutation.Prompt(); !ok {
		return &ValidationError{Name: "prompt", err: errors.New(`ent: missing required field "UserImageGeneration.prompt"`)}
	}
	if v, ok := _c.mutation.Prompt(); ok {
		if err := userimagegeneration.PromptValidator(v); err != nil {
			return &ValidationError{Name: "prompt", err: fmt.Errorf(`ent: validator failed for field "UserImageGeneration.prompt": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`ent: missing required field "UserImageGeneration.model"`)}
	}
	if v, ok := _c.mutation.Model(); ok {
		if err := userimagegeneration.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "UserImageGeneration.model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MimeType(); !ok {
		return &ValidationError{Name: "mime_type", err: errors.New(`ent: missing required field "UserImageGeneration.mime_type"`)}
	}
	if v, ok := _c.mutation.MimeType(); ok {
		if err := userimagegeneration.MimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mime_type", err: fmt.Errorf(`ent: validator failed for field "UserImageGeneration.mime_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ImageData(); !ok {
		return &ValidationError{Name: "image_data", err: errors.New(`ent: missing required field "UserImageGeneration.image_data"`)}
	}
	if v, ok := _c.mutation.ImageData(); ok {
		if err := userimagegeneration.ImageDataValidator(v); err != nil {
			return &ValidationError{Name: "image_data", err: fmt.Errorf(`ent: validator failed for field "UserImageGeneration.image_data": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ImageSha256(); !ok {
		return &ValidationError{Name: "image_sha256", err: errors.New(`ent: missing required field "UserImageGeneration.image_sha256"`)}
	}
	if v, ok := _c.mutation.ImageSha256(); ok {
		if err := userimagegeneration.ImageSha256Validator(v); err != nil {
			return &ValidationError{Name: "image_sha256", err: fmt.Errorf(`ent: validator failed for field "UserImageGeneration.image_sha256": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserImageGeneration.created_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "UserImageGeneration.user"`)}
	}
	return nil
}

func (_c *UserImageGenerationCreate) sqlSave(ctx context.Context) (*UserImageGeneration, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserImageGenerationCreate) createSpec() (*UserImageGeneration, *sqlgraph.CreateSpec) {
	var (
		_node = &UserImageGeneration{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(userimagegeneration.Table, sqlgraph.NewFieldSpec(userimagegeneration.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Prompt(); ok {
		_spec.SetField(userimagegeneration.FieldPrompt, field.TypeString, value)
		_node.Prompt = value
	}
	if value, ok := _c.mutation.RevisedPrompt(); ok {
		_spec.SetField(userimagegeneration.FieldRevisedPrompt, field.TypeString, value)
		_node.RevisedPrompt = &value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(userimagegeneration.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.MimeType(); ok {
		_spec.SetField(userimagegeneration.FieldMimeType, field.TypeString, value)
		_node.MimeType = value
	}
	if value, ok := _c.mutation.ImageData(); ok {
		_spec.SetField(userimagegeneration.FieldImageData, field.TypeBytes, value)
		_node.ImageData = value
	}
	if value, ok := _c.mutation.ImageSha256(); ok {
		_spec.SetField(userimagegeneration.FieldImageSha256, field.TypeString, value)
		_node.ImageSha256 = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(userimagegeneration.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userimagegeneration.UserTable,
			Columns: []string{userimagegeneration.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserImageGeneration.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserImageGenerationUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *UserImageGenerationCreate) OnConflict(opts ...sql.ConflictOption) *UserImageGenerationUpsertOne {
	_c.conflict = opts
	return &UserImageGenerationUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserImageGeneration.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserImageGenerationCreate) OnConflictColumns(columns ...string) *UserImageGenerationUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserImageGenerationUpsertOne{
		create: _c,
	}
}

type (
	// UserImageGenerationUpsertOne is the builder for "upsert"-ing
	//  one UserImageGeneration node.
	UserImageGenerationUpsertOne struct {
		create *UserImageGenerationCreate
	}

	// UserImageGenerationUpsert is the "OnConflict" setter.
	UserImageGenerationUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *UserImageGenerationUpsert) SetUserID(v int64) *UserImageGenerationUpsert {
	u.Set(userimagegeneration.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserImageGenerationUpsert) UpdateUserID() *UserImageGenerationUpsert {
	u.SetExcluded(userimagegeneration.FieldUserID)
	return u
}

// SetPrompt sets the "prompt" field.
func (u *UserImageGenerationUpsert) SetPrompt(v string) *UserImageGenerationUpsert {
	u.Set(userimagegeneration.FieldPrompt, v)
	return u
}

// UpdatePrompt sets the "prompt" field to the value that was provided on create.
func (u *UserImageGenerationUpsert) UpdatePrompt() *UserImageGenerationUpsert {
	u.SetExcluded(userimagegeneration.FieldPrompt)
	return u
}

// SetRevisedPrompt sets the "revised_prompt" field.
func (u *UserImageGenerationUpsert) SetRevisedPrompt(v string) *UserImageGenerationUpsert {
	u.Set(userimagegeneration.FieldRevisedPrompt, v)
	return u
}

// UpdateRevisedPrompt sets the "revised_prompt" field to the value that was provided on create.
func (u *UserImageGenerationUpsert) UpdateRevisedPrompt() *UserImageGenerationUpsert {
	u.SetExcluded(userimagegeneration.FieldRevisedPrompt)
	return u
}

// ClearRevisedPrompt clears the value of the "revised_prompt" field.
func (u *UserImageGenerationUpsert) ClearRevisedPrompt() *UserImageGenerationUpsert {
	u.SetNull(userimagegeneration.FieldRevisedPrompt)
	return u
}

// SetModel sets the "model" field.
func (u *UserImageGenerationUpsert) SetModel(v string) *UserImageGenerationUpsert {
	u.Set(userimagegeneration.FieldModel, v)
	return u
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *UserImageGenerationUpsert) UpdateModel() *UserImageGenerationUpsert {
	u.SetExcluded(userimagegeneration.FieldModel)
	return u
}

// SetMimeType sets the "mime_type" field.
func (u *UserImageGenerationUpsert) SetMimeType(v string) *UserImageGenerationUpsert {
	u.Set(userimagegeneration.FieldMimeType, v)
	return u
}

// UpdateMimeType sets the "mime_type" field to the value that was provided on create.
func (u *UserImageGenerationUpsert) UpdateMimeType() *UserImageGenerationUpsert {
	u.SetExcluded(userimagegeneration.FieldMimeType)
	return u
}

// SetImageData sets the "image_data" field.
func (u *UserImageGenerationUpsert) SetImageData(v []byte) *UserImageGenerationUpsert {
	u.Set(userimagegeneration.FieldImageData, v)
	return u
}

// UpdateImageData sets the "image_data" field to the value that was provided on create.
func (u *UserImageGenerationUpsert) UpdateImageData() *UserImageGenerationUpsert {
	u.SetExcluded(userimagegeneration.FieldImageData)
	return u
}

// SetImageSha256 sets the "image_sha256" field.
func (u *UserImageGenerationUpsert) SetImageSha256(v string) *UserImageGenerationUpsert {
	u.Set(userimagegeneration.FieldImageSha256, v)
	return u
}

// UpdateImageSha256 sets the "image_sha256" field to the value that was provided on create.
func (u *UserImageGenerationUpsert) UpdateImageSha256() *UserImageGenerationUpsert {
	u.SetExcluded(userimagegeneration.FieldImageSha256)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UserImageGeneration.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserImageGenerationUpsertOne) UpdateNewValues() *UserImageGenerationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(userimagegeneration.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserImageGeneration.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UserImageGenerationUpsertOne) Ignore() *UserImageGenerationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserImageGenerationUpsertOne) DoNothing() *UserImageGenerationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserImageGenerationCreate.OnConflict
// documentation for more info.
func (u *UserImageGenerationUpsertOne) Update(set func(*UserImageGenerationUpsert)) *UserImageGenerationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserImageGenerationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserImageGenerationUpsertOne) SetUserID(v int64) *UserImageGenerationUpsertOne {
	return u.Update(func(s *UserImageGenerationUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserImageGenerationUpsertOne) UpdateUserID() *UserImageGenerationUpsertOne {
	return u.Update(func(s *UserImageGenerationUpsert) {
		s.UpdateUserID()
	})
}

// SetPrompt sets the "prompt" field.
func (u *UserImageGenerationUpsertOne) SetPrompt(v string) *UserImageGenerationUpsertOne {
	return u.Update(func(s *UserImageGenerationUpsert) {
		s.SetPrompt(v)
	})
}

// UpdatePrompt sets the "prompt" field to the value that was provided on create.
func (u *UserImageGenerationUpsertOne) UpdatePrompt() *UserImageGenerationUpsertOne {
	return u.Update(func(s *UserImageGenerationUpsert) {
		s.UpdatePrompt()
	})
}

// SetRevisedPrompt sets the "revised_prompt" field.
func (u *UserImageGenerationUpsertOne) SetRevisedPrompt(v string) *UserImageGenerationUpsertOne {
	return u.Update(func(s *UserImageGenerationUpsert) {
		s.SetRevisedPrompt(v)
	})
}

// UpdateRevisedPrompt sets the "revised_prompt" field to the value that was provided on create.
func (u *UserImageGenerationUpsertOne) UpdateRevisedPrompt() *UserImageGenerationUpsertOne {
	return u.Update(func(s *UserImageGenerationUpsert) {
		s.UpdateRevisedPrompt()
	})
}

// ClearRevisedPrompt clears the value of the "revised_prompt" field.
func (u *UserImageGenerationUpsertOne) ClearRevisedPrompt() *UserImageGenerationUpsertOne {
	return u.Update(func(s *UserImageGenerationUpsert) {
		s.ClearRevisedPrompt()
	})
}

// SetModel sets the "model" field.
func (u *UserImageGenerationUpsertOne) SetModel(v string) *UserImageGenerationUpsertOne {
	return u.Update(func(s *UserImageGenerationUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *UserImageGenerationUpsertOne) UpdateModel() *UserImageGenerationUpsertOne {
	return u.Update(func(s *UserImageGenerationUpsert) {
		s.UpdateModel()
	})
}

// SetMimeType sets the "mime_type" field.
func (u *UserImageGenerationUpsertOne) SetMimeType(v string) *UserImageGenerationUpsertOne {
	return u.Update(func(s *UserImageGenerationUpsert) {
		s.SetMimeType(v)
	})
}

// UpdateMimeType sets the "mime_type" field to the value that was provided on create.
func (u *UserImageGenerationUpsertOne) UpdateMimeType() *UserImageGenerationUpsertOne {
	return u.Update(func(s *UserImageGenerationUpsert) {
		s.UpdateMimeType()
	})
}

// SetImageData sets the "image_data" field.
func (u *UserImageGenerationUpsertOne) SetImageData(v []byte) *UserImageGenerationUpsertOne {
	return u.Update(func(s *UserImageGenerationUpsert) {
		s.SetImageData(v)
	})
}

// UpdateImageData sets the "image_data" field to the value that was provided on create.
func (u *UserImageGenerationUpsertOne) UpdateImageData() *UserImageGenerationUpsertOne {
	return u.Update(func(s *UserImageGenerationUpsert) {
		s.UpdateImageData()
	})
}

// SetImageSha256 sets the "image_sha256" field.
func (u *UserImageGenerationUpsertOne) SetImageSha256(v string) *UserImageGenerationUpsertOne {
	return u.Update(func(s *UserImageGenerationUpsert) {
		s.SetImageSha256(v)
	})
}

// UpdateImageSha256 sets the "image_sha256" field to the value that was provided on create.
func (u *UserImageGenerationUpsertOne) UpdateImageSha256() *UserImageGenerationUpsertOne {
	return u.Update(func(s *UserImageGenerationUpsert) {
		s.UpdateImageSha256()
	})
}

// Exec executes the query.
func (u *UserImageGenerationUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserImageGenerationCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserImageGenerationUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UserImageGenerationUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UserImageGenerationUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UserImageGenerationCreateBulk is the builder for creating many UserImageGeneration entities in bulk.
type UserImageGenerationCreateBulk struct {
	config
	err      error
	builders []*UserImageGenerationCreate
	conflict []sql.ConflictOption
}

// Save creates the UserImageGeneration entities in the database.
func (_c *UserImageGenerationCreateBulk) Save(ctx context.Context) ([]*UserImageGeneration, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserImageGeneration, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserImageGenerationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserImageGenerationCreateBulk) SaveX(ctx context.Context) []*UserImageGeneration {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserImageGenerationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserImageGenerationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserImageGeneration.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserImageGenerationUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *UserImageGenerationCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserImageGenerationUpsertBulk {
	_c.conflict = opts
	return &UserImageGenerationUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserImageGeneration.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserImageGenerationCreateBulk) OnConflictColumns(columns ...string) *UserImageGenerationUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserImageGenerationUpsertBulk{
		create: _c,
	}
}

// UserImageGenerationUpsertBulk is the builder for "upsert"-ing
// a bulk of UserImageGeneration nodes.
type UserImageGenerationUpsertBulk struct {
	create *UserImageGenerationCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UserImageGeneration.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserImageGenerationUpsertBulk) UpdateNewValues() *UserImageGenerationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(userimagegeneration.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserImageGeneration.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UserImageGenerationUpsertBulk) Ignore() *UserImageGenerationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserImageGenerationUpsertBulk) DoNothing() *UserImageGenerationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserImageGenerationCreateBulk.OnConflict
// documentation for more info.
func (u *UserImageGenerationUpsertBulk) Update(set func(*UserImageGenerationUpsert)) *UserImageGenerationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserImageGenerationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserImageGenerationUpsertBulk) SetUserID(v int64) *UserImageGenerationUpsertBulk {
	return u.Update(func(s *UserImageGenerationUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserImageGenerationUpsertBulk) UpdateUserID() *UserImageGenerationUpsertBulk {
	return u.Update(func(s *UserImageGenerationUpsert) {
		s.UpdateUserID()
	})
}

// SetPrompt sets the "prompt" field.
func (u *UserImageGenerationUpsertBulk) SetPrompt(v string) *UserImageGenerationUpsertBulk {
	return u.Update(func(s *UserImageGenerationUpsert) {
		s.SetPrompt(v)
	})
}

// UpdatePrompt sets the "prompt" field to the value that was provided on create.
func (u *UserImageGenerationUpsertBulk) UpdatePrompt() *UserImageGenerationUpsertBulk {
	return u.Update(func(s *UserImageGenerationUpsert) {
		s.UpdatePrompt()
	})
}

// SetRevisedPrompt sets the "revised_prompt" field.
func (u *UserImageGenerationUpsertBulk) SetRevisedPrompt(v string) *UserImageGenerationUpsertBulk {
	return u.Update(func(s *UserImageGenerationUpsert) {
		s.SetRevisedPrompt(v)
	})
}

// UpdateRevisedPrompt sets the "revised_prompt" field to the value that was provided on create.
func (u *UserImageGenerationUpsertBulk) UpdateRevisedPrompt() *UserImageGenerationUpsertBulk {
	return u.Update(func(s *UserImageGenerationUpsert) {
		s.UpdateRevisedPrompt()
	})
}

// ClearRevisedPrompt clears the value of the "revised_prompt" field.
func (u *UserImageGenerationUpsertBulk) ClearRevisedPrompt() *UserImageGenerationUpsertBulk {
	return u.Update(func(s *UserImageGenerationUpsert) {
		s.ClearRevisedPrompt()
	})
}

// SetModel sets the "model" field.
func (u *UserImageGenerationUpsertBulk) SetModel(v string) *UserImageGenerationUpsertBulk {
	return u.Update(func(s *UserImageGenerationUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *UserImageGenerationUpsertBulk) UpdateModel() *UserImageGenerationUpsertBulk {
	return u.Update(func(s *UserImageGenerationUpsert) {
		s.UpdateModel()
	})
}

// SetMimeType sets the "mime_type" field.
func (u *UserImageGenerationUpsertBulk) SetMimeType(v string) *UserImageGenerationUpsertBulk {
	return u.Update(func(s *UserImageGenerationUpsert) {
		s.SetMimeType(v)
	})
}

// UpdateMimeType sets the "mime_type" field to the value that was provided on create.
func (u *UserImageGenerationUpsertBulk) UpdateMimeType() *UserImageGenerationUpsertBulk {
	return u.Update(func(s *UserImageGenerationUpsert) {
		s.UpdateMimeType()
	})
}

// SetImageData sets the "image_data" field.
func (u *UserImageGenerationUpsertBulk) SetImageData(v []byte) *UserImageGenerationUpsertBulk {
	return u.Update(func(s *UserImageGenerationUpsert) {
		s.SetImageData(v)
	})
}

// UpdateImageData sets the "image_data" field to the value that was provided on create.
func (u *UserImageGenerationUpsertBulk) UpdateImageData() *UserImageGenerationUpsertBulk {
	return u.Update(func(s *UserImageGenerationUpsert) {
		s.UpdateImageData()
	})
}

// SetImageSha256 sets the "image_sha256" field.
func (u *UserImageGenerationUpsertBulk) SetImageSha256(v string) *UserImageGenerationUpsertBulk {
	return u.Update(func(s *UserImageGenerationUpsert) {
		s.SetImageSha256(v)
	})
}

// UpdateImageSha256 sets the "image_sha256" field to the value that was provided on create.
func (u *UserImageGenerationUpsertBulk) UpdateImageSha256() *UserImageGenerationUpsertBulk {
	return u.Update(func(s *UserImageGenerationUpsert) {
		s.UpdateImageSha256()
	})
}

// Exec executes the query.
func (u *UserImageGenerationUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserImageGenerationCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserImageGenerationCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserImageGenerationUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
