// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Mist-wu/sub2api/ent/predicate"
	"github.com/Mist-wu/sub2api/ent/user"
	"github.com/Mist-wu/sub2api/ent/userimagegeneration"
)

// UserImageGenerationUpdate is the builder for updating UserImageGeneration entities.
type UserImageGenerationUpdate struct {
	config
	hooks    []Hook
	mutation *UserImageGenerationMutation
}

// Where appends a list predicates to the UserImageGenerationUpdate builder.
func (_u *UserImageGenerationUpdate) Where(ps ...predicate.UserImageGeneration) *UserImageGenerationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserImageGenerationUpdate) SetUserID(v int64) *UserImageGenerationUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserImageGenerationUpdate) SetNillableUserID(v *int64) *UserImageGenerationUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetPrompt sets the "prompt" field.
func (_u *UserImageGenerationUpdate) SetPrompt(v string) *UserImageGenerationUpdate {
	_u.mutation.SetPrompt(v)
	return _u
}

// SetNillablePrompt sets the "prompt" field if the given value is not nil.
func (_u *UserImageGenerationUpdate) SetNillablePrompt(v *string) *UserImageGenerationUpdate {
	if v != nil {
		_u.SetPrompt(*v)
	}
	return _u
}

// SetRevisedPrompt sets the "revised_prompt" field.
func (_u *UserImageGenerationUpdate) SetRevisedPrompt(v string) *UserImageGenerationUpdate {
	_u.mutation.SetRevisedPrompt(v)
	return _u
}

// SetNillableRevisedPrompt sets the "revised_prompt" field if the given value is not nil.
func (_u *UserImageGenerationUpdate) SetNillableRevisedPrompt(v *string) *UserImageGenerationUpdate {
	if v != nil {
		_u.SetRevisedPrompt(*v)
	}
	return _u
}

// ClearRevisedPrompt clears the value of the "revised_prompt" field.
func (_u *UserImageGenerationUpdate) ClearRevisedPrompt() *UserImageGenerationUpdate {
	_u.mutation.ClearRevisedPrompt()
	return _u
}

// SetModel sets the "model" field.
func (_u *UserImageGenerationUpdate) SetModel(v string) *UserImageGenerationUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *UserImageGenerationUpdate) SetNillableModel(v *string) *UserImageGenerationUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetMimeType sets the "mime_type" field.
func (_u *UserImageGenerationUpdate) SetMimeType(v string) *UserImageGenerationUpdate {
	_u.mutation.SetMimeType(v)
	return _u
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (_u *UserImageGenerationUpdate) SetNillableMimeType(v *string) *UserImageGenerationUpdate {
	if v != nil {
		_u.SetMimeType(*v)
	}
	return _u
}

// SetImageData sets the "image_data" field.
func (_u *UserImageGenerationUpdate) SetImageData(v []byte) *UserImageGenerationUpdate {
	_u.mutation.SetImageData(v)
	return _u
}

// SetImageSha256 sets the "image_sha256" field.
func (_u *UserImageGenerationUpdate) SetImageSha256(v string) *UserImageGenerationUpdate {
	_u.mutation.SetImageSha256(v)
	return _u
}

// SetNillableImageSha256 sets the "image_sha256" field if the given value is not nil.
func (_u *UserImageGenerationUpdate) SetNillableImageSha256(v *string) *UserImageGenerationUpdate {
	if v != nil {
		_u.SetImageSha256(*v)
	}
	return _u
}

// SetThumbnailData sets the "thumbnail_data" field.
func (_u *UserImageGenerationUpdate) SetThumbnailData(v []byte) *UserImageGenerationUpdate {
	_u.mutation.SetThumbnailData(v)
	return _u
}

// ClearThumbnailData clears the value of the "thumbnail_data" field.
func (_u *UserImageGenerationUpdate) ClearThumbnailData() *UserImageGenerationUpdate {
	_u.mutation.ClearThumbnailData()
	return _u
}

// SetThumbnailMimeType sets the "thumbnail_mime_type" field.
func (_u *UserImageGenerationUpdate) SetThumbnailMimeType(v string) *UserImageGenerationUpdate {
	_u.mutation.SetThumbnailMimeType(v)
	return _u
}

// SetNillableThumbnailMimeType sets the "thumbnail_mime_type" field if the given value is not nil.
func (_u *UserImageGenerationUpdate) SetNillableThumbnailMimeType(v *string) *UserImageGenerationUpdate {
	if v != nil {
		_u.SetThumbnailMimeType(*v)
	}
	return _u
}

// ClearThumbnailMimeType clears the value of the "thumbnail_mime_type" field.
func (_u *UserImageGenerationUpdate) ClearThumbnailMimeType() *UserImageGenerationUpdate {
	_u.mutation.ClearThumbnailMimeType()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserImageGenerationUpdate) SetUser(v *User) *UserImageGenerationUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the UserImageGenerationMutation object of the builder.
func (_u *UserImageGenerationUpdate) Mutation() *UserImageGenerationMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserImageGenerationUpdate) ClearUser() *UserImageGenerationUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserImageGenerationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserImageGenerationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserImageGenerationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserImageGenerationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserImageGenerationUpdate) check() error {
	if v, ok := _u.mutation.Prompt(); ok {
		if err := userimagegeneration.PromptValidator(v); err != nil {
			return &ValidationError{Name: "prompt", err: fmt.Errorf(`ent: validator failed for field "UserImageGeneration.prompt": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := userimagegeneration.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "UserImageGeneration.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MimeType(); ok {
		if err := userimagegeneration.MimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mime_type", err: fmt.Errorf(`ent: validator failed for field "UserImageGeneration.mime_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ImageData(); ok {
		if err := userimagegeneration.ImageDataValidator(v); err != nil {
			return &ValidationError{Name: "image_data", err: fmt.Errorf(`ent: validator failed for field "UserImageGeneration.image_data": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ImageSha256(); ok {
		if err := userimagegeneration.ImageSha256Validator(v); err != nil {
			return &ValidationError{Name: "image_sha256", err: fmt.Errorf(`ent: validator failed for field "UserImageGeneration.image_sha256": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ThumbnailMimeType(); ok {
		if err := userimagegeneration.ThumbnailMimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "thumbnail_mime_type", err: fmt.Errorf(`ent: validator failed for field "UserImageGeneration.thumbnail_mime_type": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserImageGeneration.user"`)
	}
	return nil
}

func (_u *UserImageGenerationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userimagegeneration.Table, userimagegeneration.Columns, sqlgraph.NewFieldSpec(userimagegeneration.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Prompt(); ok {
		_spec.SetField(userimagegeneration.FieldPrompt, field.TypeString, value)
	}
	if value, ok := _u.mutation.RevisedPrompt(); ok {
		_spec.SetField(userimagegeneration.FieldRevisedPrompt, field.TypeString, value)
	}
	if _u.mutation.RevisedPromptCleared() {
		_spec.ClearField(userimagegeneration.FieldRevisedPrompt, field.TypeString)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(userimagegeneration.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.MimeType(); ok {
		_spec.SetField(userimagegeneration.FieldMimeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ImageData(); ok {
		_spec.SetField(userimagegeneration.FieldImageData, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.ImageSha256(); ok {
		_spec.SetField(userimagegeneration.FieldImageSha256, field.TypeString, value)
	}
	if value, ok := _u.mutation.ThumbnailData(); ok {
		_spec.SetField(userimagegeneration.FieldThumbnailData, field.TypeBytes, value)
	}
	if _u.mutation.ThumbnailDataCleared() {
		_spec.ClearField(userimagegeneration.FieldThumbnailData, field.TypeBytes)
	}
	if value, ok := _u.mutation.ThumbnailMimeType(); ok {
		_spec.SetField(userimagegeneration.FieldThumbnailMimeType, field.TypeString, value)
	}
	if _u.mutation.ThumbnailMimeTypeCleared() {
		_spec.ClearField(userimagegeneration.FieldThumbnailMimeType, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userimagegeneration.UserTable,
			Columns: []string{userimagegeneration.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userimagegeneration.UserTable,
			Columns: []string{userimagegeneration.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userimagegeneration.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserImageGenerationUpdateOne is the builder for updating a single UserImageGeneration entity.
type UserImageGenerationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserImageGenerationMutation
}

// SetUserID sets the "user_id" field.
func (_u *UserImageGenerationUpdateOne) SetUserID(v int64) *UserImageGenerationUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserImageGenerationUpdateOne) SetNillableUserID(v *int64) *UserImageGenerationUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetPrompt sets the "prompt" field.
func (_u *UserImageGenerationUpdateOne) SetPrompt(v string) *UserImageGenerationUpdateOne {
	_u.mutation.SetPrompt(v)
	return _u
}

// SetNillablePrompt sets the "prompt" field if the given value is not nil.
func (_u *UserImageGenerationUpdateOne) SetNillablePrompt(v *string) *UserImageGenerationUpdateOne {
	if v != nil {
		_u.SetPrompt(*v)
	}
	return _u
}

// SetRevisedPrompt sets the "revised_prompt" field.
func (_u *UserImageGenerationUpdateOne) SetRevisedPrompt(v string) *UserImageGenerationUpdateOne {
	_u.mutation.SetRevisedPrompt(v)
	return _u
}

// SetNillableRevisedPrompt sets the "revised_prompt" field if the given value is not nil.
func (_u *UserImageGenerationUpdateOne) SetNillableRevisedPrompt(v *string) *UserImageGenerationUpdateOne {
	if v != nil {
		_u.SetRevisedPrompt(*v)
	}
	return _u
}

// ClearRevisedPrompt clears the value of the "revised_prompt" field.
func (_u *UserImageGenerationUpdateOne) ClearRevisedPrompt() *UserImageGenerationUpdateOne {
	_u.mutation.ClearRevisedPrompt()
	return _u
}

// SetModel sets the "model" field.
func (_u *UserImageGenerationUpdateOne) SetModel(v string) *UserImageGenerationUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *UserImageGenerationUpdateOne) SetNillableModel(v *string) *UserImageGenerationUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetMimeType sets the "mime_type" field.
func (_u *UserImageGenerationUpdateOne) SetMimeType(v string) *UserImageGenerationUpdateOne {
	_u.mutation.SetMimeType(v)
	return _u
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (_u *UserImageGenerationUpdateOne) SetNillableMimeType(v *string) *UserImageGenerationUpdateOne {
	if v != nil {
		_u.SetMimeType(*v)
	}
	return _u
}

// SetImageData sets the "image_data" field.
func (_u *UserImageGenerationUpdateOne) SetImageData(v []byte) *UserImageGenerationUpdateOne {
	_u.mutation.SetImageData(v)
	return _u
}

// SetImageSha256 sets the "image_sha256" field.
func (_u *UserImageGenerationUpdateOne) SetImageSha256(v string) *UserImageGenerationUpdateOne {
	_u.mutation.SetImageSha256(v)
	return _u
}

// SetNillableImageSha256 sets the "image_sha256" field if the given value is not nil.
func (_u *UserImageGenerationUpdateOne) SetNillableImageSha256(v *string) *UserImageGenerationUpdateOne {
	if v != nil {
		_u.SetImageSha256(*v)
	}
	return _u
}

// SetThumbnailData sets the "thumbnail_data" field.
func (_u *UserImageGenerationUpdateOne) SetThumbnailData(v []byte) *UserImageGenerationUpdateOne {
	_u.mutation.SetThumbnailData(v)
	return _u
}

// ClearThumbnailData clears the value of the "thumbnail_data" field.
func (_u *UserImageGenerationUpdateOne) ClearThumbnailData() *UserImageGenerationUpdateOne {
	_u.mutation.ClearThumbnailData()
	return _u
}

// SetThumbnailMimeType sets the "thumbnail_mime_type" field.
func (_u *UserImageGenerationUpdateOne) SetThumbnailMimeType(v string) *UserImageGenerationUpdateOne {
	_u.mutation.SetThumbnailMimeType(v)
	return _u
}

// SetNillableThumbnailMimeType sets the "thumbnail_mime_type" field if the given value is not nil.
func (_u *UserImageGenerationUpdateOne) SetNillableThumbnailMimeType(v *string) *UserImageGenerationUpdateOne {
	if v != nil {
		_u.SetThumbnailMimeType(*v)
	}
	return _u
}

// ClearThumbnailMimeType clears the value of the "thumbnail_mime_type" field.
func (_u *UserImageGenerationUpdateOne) ClearThumbnailMimeType() *UserImageGenerationUpdateOne {
	_u.mutation.ClearThumbnailMimeType()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserImageGenerationUpdateOne) SetUser(v *User) *UserImageGenerationUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the UserImageGenerationMutation object of the builder.
func (_u *UserImageGenerationUpdateOne) Mutation() *UserImageGenerationMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserImageGenerationUpdateOne) ClearUser() *UserImageGenerationUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the UserImageGenerationUpdate builder.
func (_u *UserImageGenerationUpdateOne) Where(ps ...predicate.UserImageGeneration) *UserImageGenerationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserImageGenerationUpdateOne) Select(field string, fields ...string) *UserImageGenerationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserImageGeneration entity.
func (_u *UserImageGenerationUpdateOne) Save(ctx context.Context) (*UserImageGeneration, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserImageGenerationUpdateOne) SaveX(ctx context.Context) *UserImageGeneration {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserImageGenerationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserImageGenerationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserImageGenerationUpdateOne) check() error {
	if v, ok := _u.mutation.Prompt(); ok {
		if err := userimagegeneration.PromptValidator(v); err != nil {
			return &ValidationError{Name: "prompt", err: fmt.Errorf(`ent: validator failed for field "UserImageGeneration.prompt": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := userimagegeneration.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "UserImageGeneration.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MimeType(); ok {
		if err := userimagegeneration.MimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mime_type", err: fmt.Errorf(`ent: validator failed for field "UserImageGeneration.mime_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ImageData(); ok {
		if err := userimagegeneration.ImageDataValidator(v); err != nil {
			return &ValidationError{Name: "image_data", err: fmt.Errorf(`ent: validator failed for field "UserImageGeneration.image_data": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ImageSha256(); ok {
		if err := userimagegeneration.ImageSha256Validator(v); err != nil {
			return &ValidationError{Name: "image_sha256", err: fmt.Errorf(`ent: validator failed for field "UserImageGeneration.image_sha256": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ThumbnailMimeType(); ok {
		if err := userimagegeneration.ThumbnailMimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "thumbnail_mime_type", err: fmt.Errorf(`ent: validator failed for field "UserImageGeneration.thumbnail_mime_type": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserImageGeneration.user"`)
	}
	return nil
}

func (_u *UserImageGenerationUpdateOne) sqlSave(ctx context.Context) (_node *UserImageGeneration, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userimagegeneration.Table, userimagegeneration.Columns, sqlgraph.NewFieldSpec(userimagegeneration.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserImageGeneration.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userimagegeneration.FieldID)
		for _, f := range fields {
			if !userimagegeneration.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userimagegeneration.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Prompt(); ok {
		_spec.SetField(userimagegeneration.FieldPrompt, field.TypeString, value)
	}
	if value, ok := _u.mutation.RevisedPrompt(); ok {
		_spec.SetField(userimagegeneration.FieldRevisedPrompt, field.TypeString, value)
	}
	if _u.mutation.RevisedPromptCleared() {
		_spec.ClearField(userimagegeneration.FieldRevisedPrompt, field.TypeString)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(userimagegeneration.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.MimeType(); ok {
		_spec.SetField(userimagegeneration.FieldMimeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ImageData(); ok {
		_spec.SetField(userimagegeneration.FieldImageData, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.ImageSha256(); ok {
		_spec.SetField(userimagegeneration.FieldImageSha256, field.TypeString, value)
	}
	if value, ok := _u.mutation.ThumbnailData(); ok {
		_spec.SetField(userimagegeneration.FieldThumbnailData, field.TypeBytes, value)
	}
	if _u.mutation.ThumbnailDataCleared() {
		_spec.ClearField(userimagegeneration.FieldThumbnailData, field.TypeBytes)
	}
	if value, ok := _u.mutation.ThumbnailMimeType(); ok {
		_spec.SetField(userimagegeneration.FieldThumbnailMimeType, field.TypeString, value)
	}
	if _u.mutation.ThumbnailMimeTypeCleared() {
		_spec.ClearField(userimagegeneration.FieldThumbnailMimeType, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userimagegeneration.UserTable,
			Columns: []string{userimagegeneration.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userimagegeneration.UserTable,
			Columns: []string{userimagegeneration.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserImageGeneration{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userimagegeneration.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
