// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Mist-wu/sub2api/ent/user"
	"github.com/Mist-wu/sub2api/ent/userimagegeneration"
)

// UserImageGeneration is the model entity for the UserImageGeneration schema.
type UserImageGeneration struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// Prompt holds the value of the "prompt" field.
	Prompt string `json:"prompt,omitempty"`
	// RevisedPrompt holds the value of the "revised_prompt" field.
	RevisedPrompt *string `json:"revised_prompt,omitempty"`
	// Model holds the value of the "model" field.
	Model string `json:"model,omitempty"`
	// MimeType holds the value of the "mime_type" field.
	MimeType string `json:"mime_type,omitempty"`
	// ImageData holds the value of the "image_data" field.
	ImageData []byte `json:"image_data,omitempty"`
	// ImageSha256 holds the value of the "image_sha256" field.
	ImageSha256 string `json:"image_sha256,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserImageGenerationQuery when eager-loading is set.
	Edges        UserImageGenerationEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserImageGenerationEdges holds the relations/edges for other nodes in the graph.
type UserImageGenerationEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserImageGenerationEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserImageGeneration) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case userimagegeneration.FieldImageData:
			values[i] = new([]byte)
		case userimagegeneration.FieldID, userimagegeneration.FieldUserID:
			values[i] = new(sql.NullInt64)
		case userimagegeneration.FieldPrompt, userimagegeneration.FieldRevisedPrompt, userimagegeneration.FieldModel, userimagegeneration.FieldMimeType, userimagegeneration.FieldImageSha256:
			values[i] = new(sql.NullString)
		case userimagegeneration.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserImageGeneration fields.
func (_m *UserImageGeneration) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case userimagegeneration.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case userimagegeneration.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case userimagegeneration.FieldPrompt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field prompt", values[i])
			} else if value.Valid {
				_m.Prompt = value.String
			}
		case userimagegeneration.FieldRevisedPrompt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field revised_prompt", values[i])
			} else if value.Valid {
				_m.RevisedPrompt = new(string)
				*_m.RevisedPrompt = value.String
			}
		case userimagegeneration.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				_m.Model = value.String
			}
		case userimagegeneration.FieldMimeType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mime_type", values[i])
			} else if value.Valid {
				_m.MimeType = value.String
			}
		case userimagegeneration.FieldImageData:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field image_data", values[i])
			} else if value != nil {
				_m.ImageData = *value
			}
		case userimagegeneration.FieldImageSha256:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field image_sha256", values[i])
			} else if value.Valid {
				_m.ImageSha256 = value.String
			}
		case userimagegeneration.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserImageGeneration.
// This includes values selected through modifiers, order, etc.
func (_m *UserImageGeneration) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the UserImageGeneration entity.
func (_m *UserImageGeneration) QueryUser() *UserQuery {
	return NewUserImageGenerationClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this UserImageGeneration.
// Note that you need to call UserImageGeneration.Unwrap() before calling this method if this UserImageGeneration
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserImageGeneration) Update() *UserImageGenerationUpdateOne {
	return NewUserImageGenerationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserImageGeneration entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserImageGeneration) Unwrap() *UserImageGeneration {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserImageGeneration is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserImageGeneration) String() string {
	var builder strings.Builder
	builder.WriteString("UserImageGeneration(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("prompt=")
	builder.WriteString(_m.Prompt)
	builder.WriteString(", ")
	if v := _m.RevisedPrompt; v != nil {
		builder.WriteString("revised_prompt=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("model=")
	builder.WriteString(_m.Model)
	builder.WriteString(", ")
	builder.WriteString("mime_type=")
	builder.WriteString(_m.MimeType)
	builder.WriteString(", ")
	builder.WriteString("image_data=")
	builder.WriteString(fmt.Sprintf("%v", _m.ImageData))
	builder.WriteString(", ")
	builder.WriteString("image_sha256=")
	builder.WriteString(_m.ImageSha256)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UserImageGenerations is a parsable slice of UserImageGeneration.
type UserImageGenerations []*UserImageGeneration
