// Code generated by ent, DO NOT EDIT.

package userimagegeneration

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Mist-wu/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldEQ(FieldUserID, v))
}

// Prompt applies equality check predicate on the "prompt" field. It's identical to PromptEQ.
func Prompt(v string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldEQ(FieldPrompt, v))
}

// RevisedPrompt applies equality check predicate on the "revised_prompt" field. It's identical to RevisedPromptEQ.
func RevisedPrompt(v string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldEQ(FieldRevisedPrompt, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldEQ(FieldModel, v))
}

// MimeType applies equality check predicate on the "mime_type" field. It's identical to MimeTypeEQ.
func MimeType(v string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldEQ(FieldMimeType, v))
}

// ImageData applies equality check predicate on the "image_data" field. It's identical to ImageDataEQ.
func ImageData(v []byte) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldEQ(FieldImageData, v))
}

// ImageSha256 applies equality check predicate on the "image_sha256" field. It's identical to ImageSha256EQ.
func ImageSha256(v string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldEQ(FieldImageSha256, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldEQ(FieldCreatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldNotIn(FieldUserID, vs...))
}

// PromptEQ applies the EQ predicate on the "prompt" field.
func PromptEQ(v string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldEQ(FieldPrompt, v))
}

// PromptNEQ applies the NEQ predicate on the "prompt" field.
func PromptNEQ(v string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldNEQ(FieldPrompt, v))
}

// PromptIn applies the In predicate on the "prompt" field.
func PromptIn(vs ...string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldIn(FieldPrompt, vs...))
}

// PromptNotIn applies the NotIn predicate on the "prompt" field.
func PromptNotIn(vs ...string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldNotIn(FieldPrompt, vs...))
}

// PromptGT applies the GT predicate on the "prompt" field.
func PromptGT(v string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldGT(FieldPrompt, v))
}

// PromptGTE applies the GTE predicate on the "prompt" field.
func PromptGTE(v string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldGTE(FieldPrompt, v))
}

// PromptLT applies the LT predicate on the "prompt" field.
func PromptLT(v string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldLT(FieldPrompt, v))
}

// PromptLTE applies the LTE predicate on the "prompt" field.
func PromptLTE(v string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldLTE(FieldPrompt, v))
}

// PromptContains applies the Contains predicate on the "prompt" field.
func PromptContains(v string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldContains(FieldPrompt, v))
}

// PromptHasPrefix applies the HasPrefix predicate on the "prompt" field.
func PromptHasPrefix(v string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldHasPrefix(FieldPrompt, v))
}

// PromptHasSuffix applies the HasSuffix predicate on the "prompt" field.
func PromptHasSuffix(v string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldHasSuffix(FieldPrompt, v))
}

// PromptEqualFold applies the EqualFold predicate on the "prompt" field.
func PromptEqualFold(v string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldEqualFold(FieldPrompt, v))
}

// PromptContainsFold applies the ContainsFold predicate on the "prompt" field.
func PromptContainsFold(v string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldContainsFold(FieldPrompt, v))
}

// RevisedPromptEQ applies the EQ predicate on the "revised_prompt" field.
func RevisedPromptEQ(v string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldEQ(FieldRevisedPrompt, v))
}

// RevisedPromptNEQ applies the NEQ predicate on the "revised_prompt" field.
func RevisedPromptNEQ(v string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldNEQ(FieldRevisedPrompt, v))
}

// RevisedPromptIn applies the In predicate on the "revised_prompt" field.
func RevisedPromptIn(vs ...string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldIn(FieldRevisedPrompt, vs...))
}

// RevisedPromptNotIn applies the NotIn predicate on the "revised_prompt" field.
func RevisedPromptNotIn(vs ...string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldNotIn(FieldRevisedPrompt, vs...))
}

// RevisedPromptGT applies the GT predicate on the "revised_prompt" field.
func RevisedPromptGT(v string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldGT(FieldRevisedPrompt, v))
}

// RevisedPromptGTE applies the GTE predicate on the "revised_prompt" field.
func RevisedPromptGTE(v string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldGTE(FieldRevisedPrompt, v))
}

// RevisedPromptLT applies the LT predicate on the "revised_prompt" field.
func RevisedPromptLT(v string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldLT(FieldRevisedPrompt, v))
}

// RevisedPromptLTE applies the LTE predicate on the "revised_prompt" field.
func RevisedPromptLTE(v string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldLTE(FieldRevisedPrompt, v))
}

// RevisedPromptContains applies the Contains predicate on the "revised_prompt" field.
func RevisedPromptContains(v string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldContains(FieldRevisedPrompt, v))
}

// RevisedPromptHasPrefix applies the HasPrefix predicate on the "revised_prompt" field.
func RevisedPromptHasPrefix(v string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldHasPrefix(FieldRevisedPrompt, v))
}

// RevisedPromptHasSuffix applies the HasSuffix predicate on the "revised_prompt" field.
func RevisedPromptHasSuffix(v string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldHasSuffix(FieldRevisedPrompt, v))
}

// RevisedPromptIsNil applies the IsNil predicate on the "revised_prompt" field.
func RevisedPromptIsNil() predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldIsNull(FieldRevisedPrompt))
}

// RevisedPromptNotNil applies the NotNil predicate on the "revised_prompt" field.
func RevisedPromptNotNil() predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldNotNull(FieldRevisedPrompt))
}

// RevisedPromptEqualFold applies the EqualFold predicate on the "revised_prompt" field.
func RevisedPromptEqualFold(v string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldEqualFold(FieldRevisedPrompt, v))
}

// RevisedPromptContainsFold applies the ContainsFold predicate on the "revised_prompt" field.
func RevisedPromptContainsFold(v string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldContainsFold(FieldRevisedPrompt, v))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldHasSuffix(FieldModel, v))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldContainsFold(FieldModel, v))
}

// MimeTypeEQ applies the EQ predicate on the "mime_type" field.
func MimeTypeEQ(v string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldEQ(FieldMimeType, v))
}

// MimeTypeNEQ applies the NEQ predicate on the "mime_type" field.
func MimeTypeNEQ(v string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldNEQ(FieldMimeType, v))
}

// MimeTypeIn applies the In predicate on the "mime_type" field.
func MimeTypeIn(vs ...string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldIn(FieldMimeType, vs...))
}

// MimeTypeNotIn applies the NotIn predicate on the "mime_type" field.
func MimeTypeNotIn(vs ...string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldNotIn(FieldMimeType, vs...))
}

// MimeTypeGT applies the GT predicate on the "mime_type" field.
func MimeTypeGT(v string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldGT(FieldMimeType, v))
}

// MimeTypeGTE applies the GTE predicate on the "mime_type" field.
func MimeTypeGTE(v string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldGTE(FieldMimeType, v))
}

// MimeTypeLT applies the LT predicate on the "mime_type" field.
func MimeTypeLT(v string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldLT(FieldMimeType, v))
}

// MimeTypeLTE applies the LTE predicate on the "mime_type" field.
func MimeTypeLTE(v string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldLTE(FieldMimeType, v))
}

// MimeTypeContains applies the Contains predicate on the "mime_type" field.
func MimeTypeContains(v string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldContains(FieldMimeType, v))
}

// MimeTypeHasPrefix applies the HasPrefix predicate on the "mime_type" field.
func MimeTypeHasPrefix(v string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldHasPrefix(FieldMimeType, v))
}

// MimeTypeHasSuffix applies the HasSuffix predicate on the "mime_type" field.
func MimeTypeHasSuffix(v string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldHasSuffix(FieldMimeType, v))
}

// MimeTypeEqualFold applies the EqualFold predicate on the "mime_type" field.
func MimeTypeEqualFold(v string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldEqualFold(FieldMimeType, v))
}

// MimeTypeContainsFold applies the ContainsFold predicate on the "mime_type" field.
func MimeTypeContainsFold(v string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldContainsFold(FieldMimeType, v))
}

// ImageDataEQ applies the EQ predicate on the "image_data" field.
func ImageDataEQ(v []byte) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldEQ(FieldImageData, v))
}

// ImageDataNEQ applies the NEQ predicate on the "image_data" field.
func ImageDataNEQ(v []byte) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldNEQ(FieldImageData, v))
}

// ImageDataIn applies the In predicate on the "image_data" field.
func ImageDataIn(vs ...[]byte) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldIn(FieldImageData, vs...))
}

// ImageDataNotIn applies the NotIn predicate on the "image_data" field.
func ImageDataNotIn(vs ...[]byte) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldNotIn(FieldImageData, vs...))
}

// ImageDataGT applies the GT predicate on the "image_data" field.
func ImageDataGT(v []byte) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldGT(FieldImageData, v))
}

// ImageDataGTE applies the GTE predicate on the "image_data" field.
func ImageDataGTE(v []byte) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldGTE(FieldImageData, v))
}

// ImageDataLT applies the LT predicate on the "image_data" field.
func ImageDataLT(v []byte) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldLT(FieldImageData, v))
}

// ImageDataLTE applies the LTE predicate on the "image_data" field.
func ImageDataLTE(v []byte) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldLTE(FieldImageData, v))
}

// ImageSha256EQ applies the EQ predicate on the "image_sha256" field.
func ImageSha256EQ(v string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldEQ(FieldImageSha256, v))
}

// ImageSha256NEQ applies the NEQ predicate on the "image_sha256" field.
func ImageSha256NEQ(v string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldNEQ(FieldImageSha256, v))
}

// ImageSha256In applies the In predicate on the "image_sha256" field.
func ImageSha256In(vs ...string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldIn(FieldImageSha256, vs...))
}

// ImageSha256NotIn applies the NotIn predicate on the "image_sha256" field.
func ImageSha256NotIn(vs ...string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldNotIn(FieldImageSha256, vs...))
}

// ImageSha256GT applies the GT predicate on the "image_sha256" field.
func ImageSha256GT(v string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldGT(FieldImageSha256, v))
}

// ImageSha256GTE applies the GTE predicate on the "image_sha256" field.
func ImageSha256GTE(v string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldGTE(FieldImageSha256, v))
}

// ImageSha256LT applies the LT predicate on the "image_sha256" field.
func ImageSha256LT(v string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldLT(FieldImageSha256, v))
}

// ImageSha256LTE applies the LTE predicate on the "image_sha256" field.
func ImageSha256LTE(v string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldLTE(FieldImageSha256, v))
}

// ImageSha256Contains applies the Contains predicate on the "image_sha256" field.
func ImageSha256Contains(v string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldContains(FieldImageSha256, v))
}

// ImageSha256HasPrefix applies the HasPrefix predicate on the "image_sha256" field.
func ImageSha256HasPrefix(v string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldHasPrefix(FieldImageSha256, v))
}

// ImageSha256HasSuffix applies the HasSuffix predicate on the "image_sha256" field.
func ImageSha256HasSuffix(v string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldHasSuffix(FieldImageSha256, v))
}

// ImageSha256EqualFold applies the EqualFold predicate on the "image_sha256" field.
func ImageSha256EqualFold(v string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldEqualFold(FieldImageSha256, v))
}

// ImageSha256ContainsFold applies the ContainsFold predicate on the "image_sha256" field.
func ImageSha256ContainsFold(v string) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldContainsFold(FieldImageSha256, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.FieldLTE(FieldCreatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.UserImageGeneration {
	return predicate.UserImageGeneration(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserImageGeneration) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserImageGeneration) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserImageGeneration) predicate.UserImageGeneration {
	return predicate.UserImageGeneration(sql.NotPredicates(p))
}
